server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tribe?stringtype=unspecified&timeZone=UTC
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoint:
    health:
      show-details: always
